
#####################################################################
# FRONTEND
steps:
# - name: 'gcr.io/cloud-builders/yarn'
#   args: ['--cwd', './app' ,'install', '--ignore-engines']
# - name: 'gcr.io/cloud-builders/yarn'
#   args: ['--cwd', './app' , 'build']
#   env:
#   - 'REACT_APP_BACKEND_URI=https://disinfodex-backend-production-e2kyhghera-ue.a.run.app'
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/disinfodex-new-frontend-production:${SHORT_SHA}', './app']
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/disinfodex-new-frontend-production:${SHORT_SHA}"]
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'disinfodex-new-frontend-production', '--image', 'gcr.io/$PROJECT_ID/disinfodex-new-frontend-production:${SHORT_SHA}', '--region', 'us-east1', '--platform', 'managed']


  #####################################################################

# # BACKEND
# # build the container image
# - name: "gcr.io/cloud-builders/docker"
#   args:
#       [
#           "build",
#           "-t",
#           "gcr.io/$PROJECT_ID/disinfodex-backend-production:$SHORT_SHA",
#           "./api",
#       ]
#     # push the container image to Container Registry
# - name: "gcr.io/cloud-builders/docker"
#   args:
#       [
#           "push",
#           "gcr.io/$PROJECT_ID/disinfodex-backend-production:$SHORT_SHA",
#       ]
# # Deploy container image to Cloud Run
# - name: "gcr.io/cloud-builders/gcloud"
#   args:
#       - "run"
#       - "deploy"
#       - "disinfodex-backend-production"
#       - "--image"
#       - "gcr.io/$PROJECT_ID/disinfodex-backend-production:$SHORT_SHA"
#       - "--region"
#       - "us-east1"
#       - "--platform"
#       - "managed"
# #####################################################################

# #####################################################################
# # SYNC
# # build the container image
# - name: "gcr.io/cloud-builders/docker"
#   args:
#       [
#           "build",
#           "-t",
#           "gcr.io/$PROJECT_ID/disinfodex-sync-production:$SHORT_SHA",
#           "./sync",
#       ]
#     # push the container image to Container Registry
# - name: "gcr.io/cloud-builders/docker"
#   args:
#       [
#           "push",
#           "gcr.io/$PROJECT_ID/disinfodex-sync-production:$SHORT_SHA",
#       ]
# # Deploy container image to Cloud Run
# - name: "gcr.io/cloud-builders/gcloud"
#   args:
#       - "run"
#       - "deploy"
#       - "disinfodex-sync-production"
#       - "--image"
#       - "gcr.io/$PROJECT_ID/disinfodex-sync-production:$SHORT_SHA"
#       - "--region"
#       - "us-east1"
#       - "--platform"
#       - "managed"

#####################################################################


images:
- 'gcr.io/$PROJECT_ID/disinfodex-new-frontend-production:$SHORT_SHA'
# - "gcr.io/$PROJECT_ID/disinfodex-backend-production:$SHORT_SHA"